---
logger:
  level: "info"
database:
  url: mongodb://127.0.0.1:27017
  name: fandogh
monitoring:
  address: ":8080"
  enabled: true
telemetry:
  trace:
    enabled: true
    agent: "127.0.0.1:4317"
file_storage:
  endpoint: "127.0.0.1:9000"
  access_key: "rustfsadmin"
  secret_key: "rustfsadmin"
  use_ssl: false
  region: "us-east-1"
